apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: istio-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio
  project: default
  source:
    chart: prometheus
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.17.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true