apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: vault
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://github.com/hashicorp/vault-helm
    targetRevision: 0.23.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true